"""
Copyright (c) 2026 Richard G and contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

import psycopg
from dotenv import load_dotenv

REPO_ROOT = Path(__file__).resolve().parents[1]
DATABASE_DIR = REPO_ROOT / "database"
BACKEND_DIR = REPO_ROOT / "backend"
ENV_FILE = DATABASE_DIR / ".env"
FALLBACK_ENV_FILE = DATABASE_DIR / ".env.example"
LEGACY_ENV_FILE = BACKEND_DIR / ".env"
LEGACY_FALLBACK_ENV_FILE = BACKEND_DIR / ".env.example"
DEFAULT_OUTPUT_PATH = DATABASE_DIR / "init_seed_data.sql"


def _load_env() -> None:
    if ENV_FILE.exists():
        load_dotenv(ENV_FILE)
    elif FALLBACK_ENV_FILE.exists():
        load_dotenv(FALLBACK_ENV_FILE)
    elif LEGACY_ENV_FILE.exists():
        load_dotenv(LEGACY_ENV_FILE)
    else:
        load_dotenv(LEGACY_FALLBACK_ENV_FILE)


def _default_postgres_port() -> str:
    host_port = (os.getenv("POSTGRES_HOST_PORT") or "").strip()
    if host_port:
        return host_port
    return os.getenv("POSTGRES_PORT") or "5432"


def _get_connection_string() -> str:
    project_storage_connection_string = os.getenv("PROJECT_STORAGE_CONNECTION_STRING", "").strip()
    if project_storage_connection_string:
        return project_storage_connection_string

    postgres_user = os.getenv("POSTGRES_USER", "z_graph")
    postgres_password = os.getenv("POSTGRES_PASSWORD", "zep_graph_password")
    postgres_host = os.getenv("POSTGRES_HOST", "localhost")
    postgres_port = _default_postgres_port()
    postgres_db = os.getenv("POSTGRES_DB", "z_graph")
    return (
        f"postgresql://{postgres_user}:{postgres_password}"
        f"@{postgres_host}:{postgres_port}/{postgres_db}"
    )


def _sql_literal(value: object) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return str(value)

    text = str(value).replace("'", "''")
    return f"'{text}'"


def _jsonb_literal(value: object) -> str:
    normalized = value if isinstance(value, (dict, list)) else json.loads(str(value))
    payload = json.dumps(normalized, ensure_ascii=False)
    return f"{_sql_literal(payload)}::jsonb"


def _build_seed_sql(
    prompt_labels: list[tuple[str, str | None, str, str]],
    projects: list[tuple[str, str, str, object, str | None, str | None, str | None, str | None, str | None]],
) -> str:
    lines: list[str] = []
    lines.append("-- Auto-generated seed data for z_graph")
    lines.append("-- Generated by database/export_seed_data.py")
    lines.append("")
    lines.append("BEGIN;")
    lines.append("")

    if prompt_labels:
        lines.append("INSERT INTO prompt_labels (name, project_id, created_at, updated_at)")
        lines.append("VALUES")
        label_values: list[str] = []
        for row in prompt_labels:
            name, project_id, created_at, updated_at = row
            label_values.append(
                f"  ({_sql_literal(name)}, {_sql_literal(project_id)}, {_sql_literal(created_at)}, {_sql_literal(updated_at)})"
            )
        lines.append(",\n".join(label_values))
        lines.append("ON CONFLICT (name) DO UPDATE SET")
        lines.append("  project_id = EXCLUDED.project_id,")
        lines.append("  created_at = EXCLUDED.created_at,")
        lines.append("  updated_at = EXCLUDED.updated_at;")
        lines.append("")

    if projects:
        lines.append(
            "INSERT INTO projects ("
            "project_id, created_at, updated_at, project_data, extracted_text, "
            "zep_graph_id, project_workspace_id, zep_graph_address, prompt_label"
            ")"
        )
        lines.append("VALUES")
        project_values: list[str] = []
        for row in projects:
            (
                project_id,
                created_at,
                updated_at,
                project_data,
                extracted_text,
                zep_graph_id,
                project_workspace_id,
                zep_graph_address,
                prompt_label,
            ) = row
            project_values.append(
                "  ("
                f"{_sql_literal(project_id)}, "
                f"{_sql_literal(created_at)}, "
                f"{_sql_literal(updated_at)}, "
                f"{_jsonb_literal(project_data)}, "
                f"{_sql_literal(extracted_text)}, "
                f"{_sql_literal(zep_graph_id)}, "
                f"{_sql_literal(project_workspace_id)}, "
                f"{_sql_literal(zep_graph_address)}, "
                f"{_sql_literal(prompt_label)}"
                ")"
            )
        lines.append(",\n".join(project_values))
        lines.append("ON CONFLICT (project_id) DO UPDATE SET")
        lines.append("  created_at = EXCLUDED.created_at,")
        lines.append("  updated_at = EXCLUDED.updated_at,")
        lines.append("  project_data = EXCLUDED.project_data,")
        lines.append("  extracted_text = EXCLUDED.extracted_text,")
        lines.append("  zep_graph_id = EXCLUDED.zep_graph_id,")
        lines.append("  project_workspace_id = EXCLUDED.project_workspace_id,")
        lines.append("  zep_graph_address = EXCLUDED.zep_graph_address,")
        lines.append("  prompt_label = EXCLUDED.prompt_label;")
        lines.append("")

    lines.append("COMMIT;")
    lines.append("")
    return "\n".join(lines)


def export_seed_data(output_path: Path) -> None:
    _load_env()
    connection_string = _get_connection_string()

    with psycopg.connect(connection_string) as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT name, project_id, created_at::text, updated_at::text
                FROM prompt_labels
                ORDER BY name ASC
                """
            )
            prompt_labels = cur.fetchall()

            cur.execute(
                """
                SELECT
                    project_id,
                    created_at::text,
                    updated_at::text,
                    project_data,
                    extracted_text,
                    zep_graph_id,
                    project_workspace_id,
                    zep_graph_address,
                    prompt_label
                FROM projects
                ORDER BY created_at ASC, project_id ASC
                """
            )
            projects = cur.fetchall()

    seed_sql = _build_seed_sql(prompt_labels, projects)
    output_path.write_text(seed_sql, encoding="utf-8")
    print(
        f"Seed data exported to {output_path} "
        f"(prompt_labels={len(prompt_labels)}, projects={len(projects)})"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Export current project DB rows into SQL seed file.")
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_PATH,
        help=f"Output SQL path (default: {DEFAULT_OUTPUT_PATH})",
    )
    args = parser.parse_args()
    export_seed_data(args.output.resolve())


if __name__ == "__main__":
    main()
