apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.secretName }}
  namespace: {{ include "neo4j-community.namespace" . }}
type: Opaque
stringData:
  NEO4J_AUTH: {{ .Values.auth.value | quote }}
