apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ include "neo4j-community.namespace" . }}
spec:
  selector:
    app: {{ .Values.deployment.name }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
    - name: bolt
      port: {{ .Values.service.boltPort }}
      targetPort: {{ .Values.service.boltPort }}
  type: {{ .Values.service.type }}
